
CREATE TABLE IF NOT EXISTS USERS (
    id SERIAL PRIMARY KEY,
    uuid VARCHAR(36) UNIQUE NOT NULL,
    username VARCHAR(50) UNIQUE NOT NULL,
    user_password VARCHAR(255) UNIQUE NOT NULL,
    user_role INT NOT NULL
);

ALTER TABLE USERS ADD email VARCHAR(256) UNIQUE NOT NULL;